### ISSUE TITLE
Plain Theme

### ISSUE THREAD

**Issue by brodycritchlow** [Akuli/akuli.github.io#1]
Just as a suggestion,

Use one of the built-in themes that GitHub offers. 
To do this go to Settings > Options > Github Pages > Change Theme. Find the theme then click choose them. 

Your website right now is really plain.

@Akuli

**Comment by Akuli** [comment]
Better?

**Comment by brodycritchlow** [comment]
Yes!

Thanks for listening to my idea, no one really does!
